from typing import Tuple


def measure_error(actual, predicted) -> Tuple[float, float]:
    """Returns a tuple containing the Vertex and Edge error rates, comparing an Actual/Ground Truth Graph to a Predicted Graph.

    Args:
        actual (iGraph): An Actual Graph to be compared to a Predicted Graph.
        predicted (iGraph): A Predicted Graph generated by prediction.predict_graph().
    """
    v_error = vertex_error(actual, predicted)

    e_error = edge_error(actual, predicted)

    return v_error, e_error


def vertex_error(actual, predicted):
    num_nodes_actual = abs(actual.vcount())
    num_nodes_predicted = abs(predicted.vcount())
    return ((num_nodes_predicted - num_nodes_actual) / num_nodes_actual) * 100


def edge_error(actual, predicted):
    num_edges_actual = abs(actual.ecount())
    num_edges_predicted = abs(predicted.ecount())
    return ((num_edges_predicted - num_edges_actual) / num_edges_actual) * 100
