from typing import Tuple


def measure_error(actual, predicted) -> Tuple[float, float]:
    """Returns a tuple containing the Vertex and Edge error rates, comparing an Actual/Ground Truth Graph to a Predicted Graph.

    Args:
        actual (iGraph): An Actual Graph to be compared to a Predicted Graph.
        predicted (iGraph): A Predicted Graph generated by prediction.predict_graph().

    """
    v_error = vertex_error(actual, predicted)

    e_error = edge_error(actual, predicted)

    return v_error, e_error


def vertex_error(actual, predicted):
    num_nodes_actual = abs(actual.vcount())
    num_nodes_predicted = abs(predicted.vcount())
    delta_vertex = abs(num_nodes_predicted - num_nodes_actual)
    return delta_vertex / num_nodes_actual


def edge_error(actual, predicted):
    num_edges_actual = actual.ecount()
    num_edges_predicted = predicted.ecount()
    delta_edges = abs(num_edges_predicted - num_edges_actual)
    return delta_edges / num_edges_actual
